Wrist_Joint_Controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_cust
        type: JointPositionControllerCust
    joint_name: wrist_joint
    joint_speed: 10
    motor:
        id: 0
        init: 0
        min: 205
        max: 819

Grip_Joints_Controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor_cust
        type: JointPositionControllerDualCust
    joint_name: grip_joints
    joint_speed: 10
    motor_master:
        id: 1
        init: 0
        min: 512
        max: 727
    motor_slave:
        id: 2
